// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-application/app/goproto/internal/biz"
	"kratos-application/app/goproto/internal/conf"
	"kratos-application/app/goproto/internal/data"
	"kratos-application/app/goproto/internal/server"
	"kratos-application/app/goproto/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, error) {
	db, err := data.NewDB(confData, logger)
	if err != nil {
		return nil, err
	}
	userBiz := biz.NewUserBiz(logger, db)
	userService := service.NewUserService(userBiz)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	httpServer := server.NewHTTPServer(confServer, userService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, nil
}
