// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "刷新Jwt",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token令牌",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "请求body参数",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshResponse"
                        }
                    }
                }
            }
        },
        "/auth/register_login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "注册用户",
                "parameters": [
                    {
                        "description": "请求body参数",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterLoginResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.RefreshRequest": {
            "type": "object"
        },
        "auth.RefreshResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterLoginRequest": {
            "type": "object",
            "properties": {
                "code_token": {
                    "description": "根据 type_id 方式：1=手机(不用传) 2=移动号码认证 3=微信code",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号码",
                    "type": "string"
                },
                "phone_verification": {
                    "description": "手机验证码",
                    "type": "string"
                },
                "type_id": {
                    "description": "登录注册方式：1=手机 2=移动号码认证 3=微信",
                    "allOf": [
                        {
                            "$ref": "#/definitions/elogin.LoginType"
                        }
                    ]
                }
            }
        },
        "auth.RegisterLoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/user.User"
                }
            }
        },
        "elogin.LoginType": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-comments": {
                "LoginType_TMobile": "移动号码认证",
                "LoginType_TPhone": "手机",
                "LoginType_TUnknown": "未知错误",
                "LoginType_TWechat": "微信"
            },
            "x-enum-varnames": [
                "LoginType_TUnknown",
                "LoginType_TPhone",
                "LoginType_TMobile",
                "LoginType_TWechat"
            ]
        },
        "euser.SexType": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-comments": {
                "SexType_SexFemale": "女",
                "SexType_SexMale": "男"
            },
            "x-enum-varnames": [
                "SexType_SexUnknown",
                "SexType_SexMale",
                "SexType_SexFemale"
            ]
        },
        "user.User": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "avatar_url": {
                    "description": "头像地址",
                    "type": "string"
                },
                "birthday": {
                    "description": "生日(年-月-日)",
                    "type": "string"
                },
                "cover_url": {
                    "description": "封面地址",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号码",
                    "type": "string"
                },
                "phone_area": {
                    "description": "手机国家电话区号",
                    "type": "string"
                },
                "sex": {
                    "description": "性别 1=男 2=女",
                    "allOf": [
                        {
                            "$ref": "#/definitions/euser.SexType"
                        }
                    ]
                },
                "uid": {
                    "description": "用户ID",
                    "type": "integer"
                },
                "uname": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
