// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "登录用户",
                "parameters": [
                    {
                        "description": "请求body参数",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/v1api.AuthLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1api.AuthLoginResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "刷新Jwt",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token令牌",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "请求body参数",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/v1api.AuthRefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1api.AuthRefreshResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "注册用户",
                "parameters": [
                    {
                        "description": "请求body参数",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/v1api.AuthRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1api.AuthRegisterResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1api.AuthLoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "@gotags: binding:\"required,email\"",
                    "type": "string"
                },
                "password": {
                    "description": "@gotags: binding:\"required,min=8\"",
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "v1api.AuthLoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/v1api.User"
                }
            }
        },
        "v1api.AuthRefreshRequest": {
            "type": "object"
        },
        "v1api.AuthRefreshResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "v1api.AuthRegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "@gotags: binding:\"required,email\"",
                    "type": "string"
                },
                "password": {
                    "description": "@gotags: binding:\"required,min=8\"",
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "v1api.AuthRegisterResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/v1api.User"
                }
            }
        },
        "v1api.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "uid": {
                    "type": "integer"
                },
                "uname": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "API接口",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
